name: deploy-dev

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  trigger-vercel-preview-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Set environment variable
        run: export VERCEL_URL=$VERCEL_PREVIEW_WEBHOOK_URL

      - name: Vercel preview deploy webhook
        run: "curl -H 'Content-Type: application/json' -X POST ${{ env.VERCEL_URL }}"
