name: run-tests
on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x.x
          cache: npm

      - name: Install project dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check build
        run: npm build