name: run-tests
on:
  push:
    branches:
      - '**' # matches every branch
      - '!main' # excludes master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x.x
          cache: npm

      - name: Install project dependencies
        run: npm ci

      - name: Eslint
        run: npm run lint

      - run: rm -rf ./__coverage__

      - name: Run tests
        run: npm test

      - name: Confirm coverage
        run: node ./scripts/confirm-coverage.mjs